packages:
  - apps/*
  - packages/*

catalogs:
  default:
    '@types/node': 24.10.4
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.2.3
    '@vitejs/plugin-react-swc': ^4.2.3
    cross-env: ^10.1.0
    immer: ^11.1.4
    jotai: ^2.18.0
    react: ^19.2.4
    react-aria-components: ^1.15.1
    react-dom: ^19.2.4
    react-router: ^7.13.1
    react-router-dom: ^7.13.1
    typescript: ~5.9.3
    vite: ^7.3.1
    zustand: ^5.0.11

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - puppeteer
