packages:
  - apps/*
  - packages/*

catalogs:
  default:
    '@types/node': 24.10.4
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    '@vitejs/plugin-react-swc': ^4.2.2
    cross-env: ^7.0.3
    immer: ^10.1.1
    jotai: ^2.16.0
    react: ^19.2.3
    react-aria-components: ^1.14.0
    react-dom: ^19.2.3
    react-router: ^7.11.0
    react-router-dom: ^7.11.0
    typescript: ~5.9.3
    vite: ^7.3.0
    zustand: ^5.0.9

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - puppeteer
