import React, { lazy } from 'react';

// Component map definition (code splitting)
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const componentMap: Record<string, React.LazyExoticComponent<React.ComponentType<any>>> = {
    'Button': lazy(() => import('@/shared/components/Button').then(module => ({ default: module.Button }))),
    'TextField': lazy(() => import('@/shared/components/TextField').then(module => ({ default: module.TextField }))),
    'Checkbox': lazy(() => import('@/shared/components/Checkbox').then(module => ({ default: module.Checkbox }))),
    'CheckboxGroup': lazy(() => import('@/shared/components/CheckboxGroup').then(module => ({ default: module.CheckboxGroup }))),
    'Radio': lazy(() => import('@/shared/components/Radio').then(module => ({ default: module.Radio }))),
    'RadioGroup': lazy(() => import('@/shared/components/RadioGroup').then(module => ({ default: module.RadioGroup }))),
    'Select': lazy(() => import('@/shared/components/Select').then(module => ({ default: module.Select }))),
    'ComboBox': lazy(() => import('@/shared/components/ComboBox').then(module => ({ default: module.ComboBox }))),
    'ListBox': lazy(() => import('@/shared/components/ListBox').then(module => ({ default: module.ListBox }))),
    'GridList': lazy(() => import('@/shared/components/GridList').then(module => ({ default: module.GridList }))),
    'Tree': lazy(() => import('@/shared/components/Tree').then(module => ({ default: module.Tree }))),
    'Table': lazy(() => import('@/shared/components/Table')),
    'Tabs': lazy(() => import('@/shared/components/Tabs').then(module => ({ default: module.Tabs }))),
    'Dialog': lazy(() => import('@/shared/components/Dialog').then(module => ({ default: module.Dialog }))),
    'Modal': lazy(() => import('@/shared/components/Modal').then(module => ({ default: module.Modal }))),
    'Popover': lazy(() => import('@/shared/components/Popover').then(module => ({ default: module.Popover }))),
    'ToggleButton': lazy(() => import('@/shared/components/ToggleButton').then(module => ({ default: module.ToggleButton }))),
    'ToggleButtonGroup': lazy(() => import('@/shared/components/ToggleButtonGroup').then(module => ({ default: module.ToggleButtonGroup }))),
    'TagGroup': lazy(() => import('@/shared/components/TagGroup').then(module => ({ default: module.TagGroup }))),
    'Form': lazy(() => import('@/shared/components/Form').then(module => ({ default: module.Form }))),
    'FieldGroup': lazy(() => import('@/shared/components/Field').then(module => ({ default: module.FieldGroup }))),
    'Label': lazy(() => import('@/shared/components/Field').then(module => ({ default: module.Label }))),
    'Input': lazy(() => import('@/shared/components/Field').then(module => ({ default: module.Input }))),
    'DateField': lazy(() => import('@/shared/components/DateField').then(module => ({ default: module.DateField }))),
    'DatePicker': lazy(() => import('@/shared/components/DatePicker').then(module => ({ default: module.DatePicker }))),
    'DateRangePicker': lazy(() => import('@/shared/components/DateRangePicker').then(module => ({ default: module.DateRangePicker }))),
    'TimeField': lazy(() => import('@/shared/components/TimeField').then(module => ({ default: module.TimeField }))),
    'Switch': lazy(() => import('@/shared/components/Switch').then(module => ({ default: module.Switch }))),
    'Slider': lazy(() => import('@/shared/components/Slider').then(module => ({ default: module.Slider }))),
    'Calendar': lazy(() => import('@/shared/components/Calendar').then(module => ({ default: module.Calendar }))),
    'Card': lazy(() => import('@/shared/components/Card').then(module => ({ default: module.Card }))),
    'Panel': lazy(() => import('@/shared/components/Panel').then(module => ({ default: module.Panel }))),
    'NumberField': lazy(() => import('@/shared/components/NumberField').then(module => ({ default: module.NumberField }))),
    'SearchField': lazy(() => import('@/shared/components/SearchField').then(module => ({ default: module.SearchField }))),
    'Menu': lazy(() => import('@/shared/components/Menu').then(module => ({ default: module.MenuButton }))),
    'Tooltip': lazy(() => import('@/shared/components/Tooltip').then(module => ({ default: module.Tooltip }))),
    'ProgressBar': lazy(() => import('@/shared/components/ProgressBar').then(module => ({ default: module.ProgressBar }))),
    'Meter': lazy(() => import('@/shared/components/Meter').then(module => ({ default: module.Meter }))),
    'Toolbar': lazy(() => import('@/shared/components/Toolbar').then(module => ({ default: module.Toolbar }))),
    'Separator': lazy(() => import('@/shared/components/Separator').then(module => ({ default: module.Separator }))),
};
