/**
 * TAG_SPEC_MAP — Tag → ComponentSpec 매핑 (ADR-100 Phase 6)
 *
 * ElementSprite.tsx에서 추출. StoreRenderBridge에서도 재사용.
 */

import type { ComponentSpec } from "@composition/specs";
import {
  ButtonSpec,
  BadgeSpec,
  TextSpec,
  CardSpec,
  DialogSpec,
  LinkSpec,
  PopoverSpec,
  SeparatorSpec,
  ToggleButtonSpec,
  ToggleButtonGroupSpec,
  TooltipSpec,
  TextFieldSpec,
  TextAreaSpec,
  NumberFieldSpec,
  SearchFieldSpec,
  CheckboxSpec,
  CheckboxGroupSpec,
  RadioSpec,
  RadioGroupSpec,
  SwitchSpec,
  FormSpec,
  SelectSpec,
  ComboBoxSpec,
  ListBoxSpec,
  SliderSpec,
  MeterSpec,
  ProgressBarSpec,
  TableSpec,
  TreeSpec,
  TabsSpec,
  TabListSpec,
  TabSpec,
  MenuSpec,
  BreadcrumbsSpec,
  BreadcrumbSpec,
  PaginationSpec,
  GridListSpec,
  DisclosureSpec,
  DisclosureGroupSpec,
  ToolbarSpec,
  ToastSpec,
  NavSpec,
  PanelSpec,
  GroupSpec,
  SlotSpec,
  SkeletonSpec,
  DropZoneSpec,
  FileTriggerSpec,
  MaskedFrameSpec,
  InputSpec,
  ListSpec,
  SwitcherSpec,
  DatePickerSpec,
  DateRangePickerSpec,
  DateFieldSpec,
  TimeFieldSpec,
  DateInputSpec,
  CalendarSpec,
  CalendarHeaderSpec,
  CalendarGridSpec,
  ColorPickerSpec,
  ColorFieldSpec,
  ColorSliderSpec,
  ColorAreaSpec,
  ColorWheelSpec,
  ColorSwatchSpec,
  ColorSwatchPickerSpec,
  LabelSpec,
  FieldErrorSpec,
  HeadingSpec,
  DescriptionSpec,
  SliderTrackSpec,
  ProgressBarTrackSpec,
  ProgressBarValueSpec,
  MeterTrackSpec,
  MeterValueSpec,
  SliderThumbSpec,
  SliderOutputSpec,
  DateSegmentSpec,
  SelectTriggerSpec,
  SelectValueSpec,
  SelectIconSpec,
  TagSpec,
  IconSpec,
  AvatarSpec,
  AvatarGroupSpec,
  StatusLightSpec,
  InlineAlertSpec,
  ButtonGroupSpec,
  ProgressCircleSpec,
  IllustratedMessageSpec,
  CardViewSpec,
  TableViewSpec,
} from "@composition/specs";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const TAG_SPEC_MAP: Record<string, ComponentSpec<any>> = {
  // Core components
  Button: ButtonSpec,
  Text: TextSpec,
  CheckboxGroup: CheckboxGroupSpec,
  Checkbox: CheckboxSpec,
  Switch: SwitchSpec,
  RadioGroup: RadioGroupSpec,
  Radio: RadioSpec,
  Slider: SliderSpec,
  Input: InputSpec,
  TextField: TextFieldSpec,
  SearchField: SearchFieldSpec,
  Select: SelectSpec,
  ComboBox: ComboBoxSpec,
  ProgressBar: ProgressBarSpec,
  Switcher: SwitcherSpec,
  TabBar: SwitcherSpec,
  List: ListSpec,
  MaskedFrame: MaskedFrameSpec,
  ToggleButton: ToggleButtonSpec,
  ToggleButtonGroup: ToggleButtonGroupSpec,
  ListBox: ListBoxSpec,
  Badge: BadgeSpec,
  Icon: IconSpec,
  Tag: TagSpec,
  Meter: MeterSpec,
  Separator: SeparatorSpec,
  Link: LinkSpec,
  Breadcrumbs: BreadcrumbsSpec,
  Breadcrumb: BreadcrumbSpec,
  Card: CardSpec,
  Nav: NavSpec,
  Panel: PanelSpec,
  Menu: MenuSpec,
  Tabs: TabsSpec,
  TabList: TabListSpec,
  Tab: TabSpec,
  NumberField: NumberFieldSpec,
  GridList: GridListSpec,
  Tree: TreeSpec,
  Table: TableSpec,
  Disclosure: DisclosureSpec,
  DisclosureGroup: DisclosureGroupSpec,
  Tooltip: TooltipSpec,
  Popover: PopoverSpec,
  Dialog: DialogSpec,
  ColorSwatch: ColorSwatchSpec,
  ColorSlider: ColorSliderSpec,
  TimeField: TimeFieldSpec,
  DateField: DateFieldSpec,
  ColorArea: ColorAreaSpec,
  Calendar: CalendarSpec,
  RangeCalendar: CalendarSpec,
  CalendarHeader: CalendarHeaderSpec,
  CalendarGrid: CalendarGridSpec,
  ColorWheel: ColorWheelSpec,
  DatePicker: DatePickerSpec,
  ColorPicker: ColorPickerSpec,
  DateRangePicker: DateRangePickerSpec,
  TextArea: TextAreaSpec,
  Form: FormSpec,
  Toolbar: ToolbarSpec,
  FileTrigger: FileTriggerSpec,
  DropZone: DropZoneSpec,
  Skeleton: SkeletonSpec,
  Toast: ToastSpec,
  Pagination: PaginationSpec,
  ColorField: ColorFieldSpec,
  ColorSwatchPicker: ColorSwatchPickerSpec,
  Group: GroupSpec,
  Slot: SlotSpec,
  Avatar: AvatarSpec,
  AvatarGroup: AvatarGroupSpec,
  StatusLight: StatusLightSpec,
  InlineAlert: InlineAlertSpec,
  ButtonGroup: ButtonGroupSpec,
  ProgressCircle: ProgressCircleSpec,
  IllustratedMessage: IllustratedMessageSpec,
  CardView: CardViewSpec,
  TableView: TableViewSpec,
  // child specs (compound 컴포넌트 하위 요소)
  Label: LabelSpec,
  FieldError: FieldErrorSpec,
  Heading: HeadingSpec,
  Description: DescriptionSpec,
  SliderTrack: SliderTrackSpec,
  ProgressBarTrack: ProgressBarTrackSpec,
  ProgressBarValue: ProgressBarValueSpec,
  MeterTrack: MeterTrackSpec,
  MeterValue: MeterValueSpec,
  SliderThumb: SliderThumbSpec,
  SliderOutput: SliderOutputSpec,
  DateSegment: DateSegmentSpec,
  TimeSegment: DateSegmentSpec,
  SelectTrigger: SelectTriggerSpec,
  SelectValue: SelectValueSpec,
  SelectIcon: SelectIconSpec,
  ComboBoxWrapper: SelectTriggerSpec,
  ComboBoxInput: SelectValueSpec,
  ComboBoxTrigger: SelectIconSpec,
  SearchFieldWrapper: SelectTriggerSpec,
  SearchInput: SelectValueSpec,
  SearchIcon: SelectIconSpec,
  SearchClearButton: SelectIconSpec,
  DateInput: DateInputSpec,
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function getSpecForTag(tag: string): ComponentSpec<any> | null {
  return TAG_SPEC_MAP[tag] ?? null;
}

/**
 * 텍스트 렌더링 대상 태그 (TextSprite / buildTextNodeData 경로)
 *
 * ADR-058 Phase 1: `Text`는 TEXT_TAGS + SPEC_PREFERRED_TEXT_TAGS로 유지 (spec 경로 라우팅)
 * ADR-058 Phase 2: `Heading` 제거 — TAG_SPEC_MAP 등록으로 spec 경로 자동 라우팅
 * Phase 3/4에서 Kbd/Code도 spec 전환 후 완전 폐지 예정.
 */
export const TEXT_TAGS = new Set([
  "Text",
  "Label",
  "Description",
  "Kbd",
  "Code",
  "InlineAlert",
]);

/** 이미지 렌더링 대상 태그 (ImageSprite / buildImageNodeData 경로) */
export const IMAGE_TAGS = new Set(["Image", "Avatar", "Logo", "Thumbnail"]);
